# Generated by Django 2.0.5 on 2018-05-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(db_column='building_s_id', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.Building', to_field='s_id'),
        ),
    ]
