# Generated by Django 2.0.5 on 2018-05-20 12:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180519_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Location (lat, lng)'),
        ),
        migrations.AddField(
            model_name='building',
            name='position',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Position (x, y)'),
        ),
        migrations.AddField(
            model_name='floor',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='s_id',
            field=models.IntegerField(unique=True, verbose_name='Situm ID'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(db_column='building_s_id', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.Building', to_field='s_id', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='s_id',
            field=models.IntegerField(unique=True, verbose_name='Situm ID'),
        ),
    ]
